name: Build and Publish Apache Polaris Docker Image

on:
  schedule:
    # Run every day at midnight
    - cron: '0 0 * * *'
  # Allows manual triggering
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/polaris

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write # Needed for attestation
      actions: read   # Required for attestation
      attestations: write
    
    steps:
      - name: Clone Apache Polaris repository
        run: |
          git clone https://github.com/apache/polaris.git

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          working-directory: ./polaris
      
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.13'
      
          
      - name: Build Polaris Quarkus server
        working-directory: ./polaris
        run: |
          ./gradlew \
            :polaris-quarkus-server:assemble \
            :polaris-quarkus-server:quarkusAppPartsBuild --rerun \
            -Dquarkus.container-image.build=true
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value={{date 'YYYYMMDD'}}
      
      - name: Get Polaris version and tag
        id: polaris-version
        run: |
          cd polaris
          VERSION=$(./gradlew properties | grep "version:" | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Found Polaris version: $VERSION"
          
          # Find the local Docker image
          IMAGE_ID=$(docker images | grep "apache/polaris" | awk '{print $3}' | head -n 1)
          echo "image_id=$IMAGE_ID" >> $GITHUB_OUTPUT
          echo "Found image ID: $IMAGE_ID"
      
      - name: Tag the image for GitHub packages
        run: |
          IMAGE_ID=${{ steps.polaris-version.outputs.image_id }}
          VERSION=${{ steps.polaris-version.outputs.version }}
          FULL_IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"
          
          docker tag $IMAGE_ID $FULL_IMAGE_NAME
          docker tag $IMAGE_ID ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker tag $IMAGE_ID ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
          echo "Tagged image $IMAGE_ID as $FULL_IMAGE_NAME"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Delete older package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'polaris'
          package-type: 'container'
          min-versions-to-keep: 1 # Keep only the most recent version
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Check if release exists
        id: check-release
        run: |
          VERSION="${{ steps.polaris-version.outputs.version }}"
          echo "Checking if release with tag $VERSION exists..."
          
          # Try to fetch the release information
          RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$VERSION")
          
          # Check if release exists
          if [[ $RELEASE_INFO == *"Not Found"* ]]; then
            echo "No existing release found with tag $VERSION"
            echo "should_create=true" >> $GITHUB_OUTPUT
          else
            echo "Release with tag $VERSION already exists"
            echo "should_create=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create-release
        if: steps.check-release.outputs.should_create == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.polaris-version.outputs.version }}
          release_name: Release ${{ steps.polaris-version.outputs.version }}
          draft: false
          prerelease: false
          body: |
            Release of Apache Polaris version ${{ steps.polaris-version.outputs.version }}
            
            See [CHANGELOG](https://github.com/apache/polaris/commits) for details.